Update README.md
Uniswap/widgets-demo pull request #1
Opened 2022-04-07 17:31 UTC by willhennessy

2022-04-07 17:57 UTC, zzmp requested changes

2022-04-07 17:57 UTC, zzmp commented on README.md
> +    - [nextjs branch](../../tree/nextjs)
Use the same styling (ie casing) for Next.js throughout. Most projects have a "brand" page specifying how to style their name; Next.js prefers "Next.js": https://vercel.com/design#spelling.

2022-04-07 17:57 UTC, zzmp commented on README.md
> +2. Download the remote branches by running `git branch -v -a`.
`git branch` lists branches, but `git fetch` will actually download them. However, you should already have these from cloning the repo, so this step is not necessary.

2022-04-07 17:57 UTC, zzmp commented on README.md
> +3. Switch to your chosen branch by running `git switch nextjs` or `git switch create-react-app`.
nit: With markdown, you can use 1. for every element in a numbered list. The markdown compiler will take care of numbering them for you, and this way it is easier to add to the middle of the list in the future.

2022-04-08 01:27 UTC, willhennessy commented on README.md
> +2. Download the remote branches by running `git branch -v -a`.
oh interesting. I thought it was necessary because `git branch` only lists `main` and not `nextjs` or `create-react-app`.  But yeah `git switch nextjs` works regardless. Thanks I'll remove this step!

2022-04-08 01:42 UTC, willhennessy commented
thanks for the feedback zach. I fixed everything!

2022-04-14 20:13 UTC, merged